---

- name: Install prerequisites packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - ca-certificates
    - apt-transport-https
    - docker.io

- name: Add Kubernetes key
  apt_key:
    url: "{{ kubernetes_key }}"
    state: present

- name: Add Kubernetes repository
  apt_repository:
    repo: "{{ kubernetes_repo }}"
    state: present

- name: Install kubernetes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - kubelet
    - kubectl
    - kubeadm

- name: Get Kubernetes cluster status
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: k8s_cluster

- name: Manage Worker node
  import_tasks: worker.yml
  when: inventory_hostname in groups['worker'] and k8s_cluster.stat.exists == false

- name: Manage Master node
  import_tasks: master.yml
  when: inventory_hostname in groups['master'] and k8s_cluster.stat.exists == false
