---

- name: Initialize Kubernetes master nodes
  shell: "kubeadm init --apiserver-advertise-address {{ inventory_hostname }} --pod-network-cidr {{ kubernetes_cidr }}/16"

- name: Deploy Kubernetes Canal rbac pod
  command: kubectl create -f {{ canal_rbac_repo }}
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Deploy Kubernetes Canal pod
  command: kubectl create -f {{ canal_repo }}
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Deploy Kubernetes Dashboard
  command: kubectl create -f {{ kubernetes_dashboard }}
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  ignore_errors: yes

- name: Create Kubernetes discovery token
  command: kubeadm token create {{ kubernetes_token }} --ttl {{ kubernetes_token_ttl }}
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Manage Vagrant user profile
  import_tasks: users.yml
