---

- name: Create user directory
  file:
    state: directory
    path: "/home/vagrant/.kube"
    owner: vagrant
    group: vagrant
    mode: 0755

- name: Copy Kubernetes conf file
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    owner: vagrant
    group: vagrant
    mode: 0600
    remote_src: yes
